### ISSUE TITLE
Install procedure uses python2 with setuptools that has python3 syntax

### ISSUE THREAD

**Issue by xapple** [lanzen/CREST#10]
Hi,

I was trying to use CREST to classify some OTUs and did not manage to install the program.

The first step of running `bootstrap.py` works, but the second step calling `bin/buildout` fails with the following output:

    Getting distribution for 'setuptools'.
    file e.py (for module e) not found
    file a.py (for module a) not found
    file s.py (for module s) not found
    file y.py (for module y) not found
    file _.py (for module _) not found
    file i.py (for module i) not found
    file n.py (for module n) not found
    file s.py (for module s) not found
    file t.py (for module t) not found
    file a.py (for module a) not found
    file l.py (for module l) not found
    file l.py (for module l) not found
    warning: no files found matching '*.py' under directory 'tests'
    warning: no previously-included files found matching 'pyproject.toml'
    file e.py (for module e) not found
    file a.py (for module a) not found
    file s.py (for module s) not found
    file y.py (for module y) not found
    file _.py (for module _) not found
    file i.py (for module i) not found
    file n.py (for module n) not found
    file s.py (for module s) not found
    file t.py (for module t) not found
    file a.py (for module a) not found
    file l.py (for module l) not found
    file l.py (for module l) not found
    file e.py (for module e) not found
    file a.py (for module a) not found
    file s.py (for module s) not found
    file y.py (for module y) not found
    file _.py (for module _) not found
    file i.py (for module i) not found
    file n.py (for module n) not found
    file s.py (for module s) not found
    file t.py (for module t) not found
    file a.py (for module a) not found
    file l.py (for module l) not found
    file l.py (for module l) not found
      File "build/bdist.linux-x86_64/egg/setuptools/installer.py", line 130
        raise DistutilsError(str(e)) from e
                                        ^
    SyntaxError: invalid syntax

      File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 211
        ) from e
             ^
    SyntaxError: invalid syntax

      File "build/bdist.linux-x86_64/egg/setuptools/_distutils/_msvccompiler.py", line 264
        self.ldflags_exe = [*ldflags, '/MANIFEST:EMBED,ID=1']
                            ^
    SyntaxError: invalid syntax

      File "build/bdist.linux-x86_64/egg/setuptools/_distutils/command/build.py", line 84
        plat_specifier = ".%s-%d.%d" % (self.plat_name, *sys.version_info[:2])
                                                        ^
    SyntaxError: invalid syntax

      File "build/bdist.linux-x86_64/egg/setuptools/_distutils/command/install_egg_info.py", line 27
        *sys.version_info[:2]
        ^

    [... SOME OUTPUT TRUNCATED ...]

    SyntaxError: invalid syntax

      File "/home/sinclair/programs/crest/eggs/tmpmxMozr/setuptools-49.6.0-py2.7.egg/setuptools/_distutils/command/build.py", line 84
        plat_specifier = ".%s-%d.%d" % (self.plat_name, *sys.version_info[:2])
                                                        ^
    SyntaxError: invalid syntax

      File "/home/sinclair/programs/crest/eggs/tmpmxMozr/setuptools-49.6.0-py2.7.egg/setuptools/_distutils/command/install_egg_info.py", line 27
        *sys.version_info[:2]
        ^
    SyntaxError: invalid syntax

      File "/home/sinclair/programs/crest/eggs/tmpmxMozr/setuptools-49.6.0-py2.7.egg/setuptools/command/rotate.py", line 40
        raise DistutilsOptionError("--keep must be an integer") from e
                                                                   ^
    SyntaxError: invalid syntax

      File "/home/sinclair/programs/crest/eggs/tmpmxMozr/setuptools-49.6.0-py2.7.egg/setuptools/command/easy_install.py", line 361
        ) from e
             ^
    SyntaxError: invalid syntax

      File "/home/sinclair/programs/crest/eggs/tmpmxMozr/setuptools-49.6.0-py2.7.egg/setuptools/command/egg_info.py", line 215
        ) from e
             ^
    SyntaxError: invalid syntax

      File "/home/sinclair/programs/crest/eggs/tmpmxMozr/setuptools-49.6.0-py2.7.egg/pkg_resources/__init__.py", line 1380
        raise SyntaxError(e) from e
                                ^
    SyntaxError: invalid syntax

    Got setuptools 49.6.0.
    Upgraded:
      setuptools version 49.6.0;
    restarting.
    Generated script '/home/sinclair/programs/crest/bin/buildout'.
    Traceback (most recent call last):
      File "bin/buildout", line 9, in <module>
        import zc.buildout.buildout
      File "/home/sinclair/programs/crest/eggs/zc.buildout-2.13.3-py2.7.egg/zc/buildout/buildout.py", line 18, in <module>
        import zc.buildout.easy_install
      File "/home/sinclair/programs/crest/eggs/zc.buildout-2.13.3-py2.7.egg/zc/buildout/easy_install.py", line 29, in <module>
        import setuptools.archive_util
      File "/home/sinclair/programs/crest/eggs/setuptools-49.6.0-py2.7.egg/setuptools/__init__.py", line 21, in <module>
        from setuptools.dist import Distribution
      File "/home/sinclair/programs/crest/eggs/setuptools-49.6.0-py2.7.egg/setuptools/dist.py", line 211
        ) from e
             ^
    SyntaxError: invalid syntax

This is on Ubuntu 20 LTS.

I was automating the installation procedure with a python class while encountering this error:

    class CrestClassify:

        apt_packages = ['ncbi-blast+', 'python2']
        tgz_url = "https://github.com/lanzen/CREST/releases/download/3.2.0/" \
                  "LCAClassifierV3.2.0.tar.gz"

        @classmethod
        def install(cls, prefix="~/programs/crest/"):
            """
            Will automatically download and install the CREST classifier software on
            this computer and for the current user.
            """
            # Start with required apt packages #
            install_apt_packages(cls.apt_packages, verbose=True)
            # Make a temporary directory #
            tmp_dir = new_temp_dir()
            # Download tarball #
            tgz_loc = download_from_url(cls.tgz_url, tmp_dir)
            # Uncompress #
            tgz_loc.untargz_to(tmp_dir)
            src_dir = tmp_dir.sub_directory
            src_dir.move_to(prefix)
            # This 'bootstrap' stuff can't detect paths it seems, have to cwd #
            current_dir = os.getcwd()
            os.chdir(src_dir)
            # Call the install command - step one #
            bootstrap_script = src_dir + 'bootstrap.py'
            sh.python2(bootstrap_script)
            # Call the install command - step two #
            buildout_cmd = src_dir + 'bin/buildout'
            sh.python2(buildout_cmd)
            # Restore current directory #
            os.chdir(current_dir)

**Comment by lanzen** [comment]
Hi Lucas,

It seems like the installed version of setuptools cannot be installed on your system and this is what is causing the error. It is not a CREST error as such, as you can see. I have not tried this with Ubuntu 20 yet and honestly it is very complicated to solve the dependency issues of setuptools, which seem to accumulate with each frequent release, and caused of maybe 90% of the bugs people have reported. In the end I may have to set up a bioconda environment or something for this to install it instead, and perhaps get rid of setuptools altogether but I have very limited time to maintain CREST at the moment, I am afraid.

Did you use the install.sh script, to ensure that you are running python2.7 and not python3? 

Cheers,
Anders

**Comment by blub-blub** [comment]
Hi Anders,
I am facing a similar error on Ubuntu 18.04 using the install.sh script. 
Would be very happy about a solution to this. Or a hint about how I could solve this problem locally (if that is possible?).
Cheers,
Anne 

```
bash install.sh
ez_setup.py is deprecated and when using it setuptools will be pinned to 33.1.1 since it's the last version that supports setuptools self upgrade/installation, check https://github.com/pypa/setuptools/issues/581 for more info; use pip to install setuptools
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-44.0.0.zip
Extracting in /tmp/tmp6iTyk8
Now working in /tmp/tmp6iTyk8/setuptools-44.0.0
Building a Setuptools egg in /tmp/bootstrap-G9_rVZ
warning: no files found matching '*.py' under directory 'tests'
warning: no previously-included files found matching 'pyproject.toml'
/tmp/bootstrap-G9_rVZ/setuptools-44.0.0-py2.7.egg
WARNING: The easy_install command is deprecated and will be removed in a future version.
Creating directory '/home/ente/Programme/CREST-master/LCAClassifier/eggs'.
Creating directory '/home/ente/Programme/CREST-master/LCAClassifier/bin'.
Creating directory '/home/ente/Programme/CREST-master/LCAClassifier/parts'.
Creating directory '/home/ente/Programme/CREST-master/LCAClassifier/develop-eggs'.
Generated script '/home/ente/Programme/CREST-master/LCAClassifier/bin/buildout'.
Getting distribution for 'zc.buildout>=2.12.0'.
Got zc.buildout 2.13.3.
Getting distribution for 'setuptools'.
WARNING: The easy_install command is deprecated and will be removed in a future version.
warning: no files found matching '*.py' under directory 'tests'
warning: no previously-included files found matching 'pyproject.toml'
  File "build/bdist.linux-x86_64/egg/setuptools/msvc.py", line 278
    ) from exc
         ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/setuptools/archive_util.py", line 140
    ) from e
         ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/setuptools/config.py", line 43
    ) from e
         ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/setuptools/package_index.py", line 59
    ) from e
         ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/setuptools/installer.py", line 128
    raise DistutilsError(str(e)) from e
                                    ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/setuptools/_distutils/_msvccompiler.py", line 266
    self.ldflags_exe = [*ldflags, '/MANIFEST:EMBED,ID=1']
                        ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/setuptools/_distutils/spawn.py", line 82
    "command %r failed: %s" % (cmd, exc.args[-1])) from exc
                                                      ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/setuptools/_distutils/command/build.py", line 84
    plat_specifier = ".%s-%d.%d" % (self.plat_name, *sys.version_info[:2])
                                                    ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/setuptools/_distutils/command/install_egg_info.py", line 27
    *sys.version_info[:2]
    ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 205
    ) from e
         ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 344
    ) from e
         ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/setuptools/command/egg_info.py", line 212
    ) from e
         ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/setuptools/command/rotate.py", line 38
    raise DistutilsOptionError("--keep must be an integer") from e
                                                               ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1365
    raise SyntaxError(e) from e
                            ^
SyntaxError: invalid syntax

  File "/home/ente/Programme/CREST-master/LCAClassifier/eggs/tmpvtTDd5/setuptools-50.3.0-py2.7.egg/pkg_resources/__init__.py", line 1365
    raise SyntaxError(e) from e
                            ^
SyntaxError: invalid syntax

  File "/home/ente/Programme/CREST-master/LCAClassifier/eggs/tmpvtTDd5/setuptools-50.3.0-py2.7.egg/setuptools/archive_util.py", line 140
    ) from e
         ^
SyntaxError: invalid syntax

  File "/home/ente/Programme/CREST-master/LCAClassifier/eggs/tmpvtTDd5/setuptools-50.3.0-py2.7.egg/setuptools/config.py", line 43
    ) from e
         ^
SyntaxError: invalid syntax

  File "/home/ente/Programme/CREST-master/LCAClassifier/eggs/tmpvtTDd5/setuptools-50.3.0-py2.7.egg/setuptools/dist.py", line 205
    ) from e
         ^
SyntaxError: invalid syntax

  File "/home/ente/Programme/CREST-master/LCAClassifier/eggs/tmpvtTDd5/setuptools-50.3.0-py2.7.egg/setuptools/installer.py", line 128
    raise DistutilsError(str(e)) from e
                                    ^
SyntaxError: invalid syntax

  File "/home/ente/Programme/CREST-master/LCAClassifier/eggs/tmpvtTDd5/setuptools-50.3.0-py2.7.egg/setuptools/msvc.py", line 278
    ) from exc
         ^
SyntaxError: invalid syntax

  File "/home/ente/Programme/CREST-master/LCAClassifier/eggs/tmpvtTDd5/setuptools-50.3.0-py2.7.egg/setuptools/package_index.py", line 59
    ) from e
         ^
SyntaxError: invalid syntax

  File "/home/ente/Programme/CREST-master/LCAClassifier/eggs/tmpvtTDd5/setuptools-50.3.0-py2.7.egg/setuptools/_distutils/_msvccompiler.py", line 266
    self.ldflags_exe = [*ldflags, '/MANIFEST:EMBED,ID=1']
                        ^
SyntaxError: invalid syntax

  File "/home/ente/Programme/CREST-master/LCAClassifier/eggs/tmpvtTDd5/setuptools-50.3.0-py2.7.egg/setuptools/_distutils/spawn.py", line 82
    "command %r failed: %s" % (cmd, exc.args[-1])) from exc
                                                      ^
SyntaxError: invalid syntax

  File "/home/ente/Programme/CREST-master/LCAClassifier/eggs/tmpvtTDd5/setuptools-50.3.0-py2.7.egg/setuptools/_distutils/command/build.py", line 84
    plat_specifier = ".%s-%d.%d" % (self.plat_name, *sys.version_info[:2])
                                                    ^
SyntaxError: invalid syntax

  File "/home/ente/Programme/CREST-master/LCAClassifier/eggs/tmpvtTDd5/setuptools-50.3.0-py2.7.egg/setuptools/_distutils/command/install_egg_info.py", line 27
    *sys.version_info[:2]
    ^
SyntaxError: invalid syntax

  File "/home/ente/Programme/CREST-master/LCAClassifier/eggs/tmpvtTDd5/setuptools-50.3.0-py2.7.egg/setuptools/command/easy_install.py", line 344
    ) from e
         ^
SyntaxError: invalid syntax

  File "/home/ente/Programme/CREST-master/LCAClassifier/eggs/tmpvtTDd5/setuptools-50.3.0-py2.7.egg/setuptools/command/egg_info.py", line 212
    ) from e
         ^
SyntaxError: invalid syntax

  File "/home/ente/Programme/CREST-master/LCAClassifier/eggs/tmpvtTDd5/setuptools-50.3.0-py2.7.egg/setuptools/command/rotate.py", line 38
    raise DistutilsOptionError("--keep must be an integer") from e
                                                               ^
SyntaxError: invalid syntax

Got setuptools 50.3.0.
Upgraded:
  zc.buildout version 2.13.3,
  setuptools version 50.3.0;
restarting.
Generated script '/home/ente/Programme/CREST-master/LCAClassifier/bin/buildout'.
Traceback (most recent call last):
  File "bin/buildout", line 9, in <module>
    import zc.buildout.buildout
  File "/home/ente/Programme/CREST-master/LCAClassifier/eggs/zc.buildout-2.13.3-py2.7.egg/zc/__init__.py", line 2, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/home/ente/Programme/CREST-master/LCAClassifier/eggs/setuptools-50.3.0-py2.7.egg/pkg_resources/__init__.py", line 1365
    raise SyntaxError(e) from e
                            ^
SyntaxError: invalid syntax
````

**Comment by lanzen** [comment]
Thank you!

Did you use the latest release when you got this error, because I cannot reproduce it? If not, try that and please let me know.

**Comment by blub-blub** [comment]
Hi Anders, 
thank you for the quick reply! Yes, I have just downloaded the latest version today in the morning ;) 
In the meanwhile I found the fix for my system, I have installed the python-setuptools before running the script, now it seems to have worked, at least no more errors occurred and all the files "appeared". Maybe you can add the setuptools to the installation requirements.
Best,
Anne

**Comment by lanzen** [comment]
Will do. Many thanks for sharing your experience and helping to resolve the problem!

**Comment by xapple** [comment]
There still remains an issue, the latest version doesn't install. This line should be changed:

https://github.com/lanzen/CREST/commit/43ffd3d528966d6b55013e2cff6108051f739aef#r43352939
