### ISSUE TITLE
Installation failed -- numpy version

### ISSUE THREAD

**Issue by xapple** [lanzen/CREST#2]
I just tried to install LCAClassifier. But it did not work. Here is the exact procedure and the error message:

```
mkdir -p ~/test
cd ~/test
wget https://github.com/lanzen/CREST/archive/2.0.4.zip
unzip 2.0.4.zip
cd CREST-*
mv LCAClassifier ~/programs/lca_classifier
cd ~/programs/lca_classifier
./install.sh
cd bin
./classify
```

Result:

```
RuntimeError: module compiled against API version 0xa but this version of numpy is 0x6
Traceback (most recent call last):
  File "./classify", line 16, in <module>
    import LCAClassifier.classify
  File "/home/lucas/programs/lca_classifier/src/LCAClassifier/classify.py", line 17, in <module>
    from LCAClassifier.taxa import Node, Read, Tree
  File "/home/lucas/programs/lca_classifier/src/LCAClassifier/taxa.py", line 7, in <module>
    import biom.table
  File "/home/lucas/programs/lca_classifier/eggs/biom_format-2.1.5-py2.7-linux-x86_64.egg/biom/__init__.py", line 51, in <module>
    from .table import Table
  File "/home/lucas/programs/lca_classifier/eggs/biom_format-2.1.5-py2.7-linux-x86_64.egg/biom/table.py", line 186, in <module>
    from scipy.sparse import coo_matrix, csc_matrix, csr_matrix, isspmatrix, vstack
  File "/home/lucas/programs/lca_classifier/eggs/scipy-0.17.0-py2.7-linux-x86_64.egg/scipy/sparse/__init__.py", line 214, in <module>
    from .csr import *
  File "/home/lucas/programs/lca_classifier/eggs/scipy-0.17.0-py2.7-linux-x86_64.egg/scipy/sparse/csr.py", line 13, in <module>
    from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
ImportError: numpy.core.multiarray failed to import
```

**Comment by lanzen** [comment]
Numpy / SciPy is not easily installed automatically across platforms. We are trying to address in the latest version. Until then, it would help if you could send me the error messages you should have gotten during installation. If not, then I am not sure why numpy.core.multiarray fails to import and I cannot reproduces this error. Try to just run the python that is installed with CREST (under bin/python) and then run "import numpy.core.multiarray".

**Comment by xapple** [comment]
The installation completed successfully. I didn't see any error messages. I was able to fix the problem though by commenting out the line that points to numpy in the `classify` executable. So that works for now !
