### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by TurbulentCupcake** [lanzen/CREST#4]
Hey,

I tried using ./install.sh and got this error : 

`ez_setup.py is deprecated and when using it setuptools will be pinned to 33.1.1 since it's the last version that supports setuptools self upgrade/installation, check https://github.com/pypa/setuptools/issues/581 for more info; use pip to install setuptools
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-33.1.1.zip
Extracting in /tmp/tmpXYpTxy
Now working in /tmp/tmpXYpTxy/setuptools-33.1.1
Building a Setuptools egg in /tmp/bootstrap-PBAxVw
warning: no files found matching '*' under directory 'setuptools/_vendor'
/tmp/bootstrap-PBAxVw/setuptools-33.1.1-py2.7.egg
no previously-included directories found matching 'doc'
no previously-included directories found matching 'old-tutorial'
Creating directory '/home/adithya/RDP/tfidf/PredictionsRData/kFoldCrossValidationSetup/CREST_LAB/CREST-master/LCAClassifier/develop-eggs'.
Generated script '/home/adithya/RDP/tfidf/PredictionsRData/kFoldCrossValidationSetup/CREST_LAB/CREST-master/LCAClassifier/bin/buildout'.
Upgraded:
  zc.buildout version 2.8.0,
  setuptools version 36.2.0;
restarting.
Generated script '/home/adithya/RDP/tfidf/PredictionsRData/kFoldCrossValidationSetup/CREST_LAB/CREST-master/LCAClassifier/bin/buildout'.
Develop: '/home/adithya/RDP/tfidf/PredictionsRData/kFoldCrossValidationSetup/CREST_LAB/CREST-master/LCAClassifier/.'
Installing test.
Getting distribution for 'biom-format>1.1.1'.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/adithya/RDP/tfidf/PredictionsRData/kFoldCrossValidationSetup/CREST_LAB/CREST-master/LCAClassifier/eggs/setuptools-36.2.0-py2.7.egg/setuptools/command/easy_install.py", line 2279, in main
    **kw
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/adithya/RDP/tfidf/PredictionsRData/kFoldCrossValidationSetup/CREST_LAB/CREST-master/LCAClassifier/eggs/setuptools-36.2.0-py2.7.egg/setuptools/command/easy_install.py", line 411, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/adithya/RDP/tfidf/PredictionsRData/kFoldCrossValidationSetup/CREST_LAB/CREST-master/LCAClassifier/eggs/setuptools-36.2.0-py2.7.egg/setuptools/command/easy_install.py", line 653, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/adithya/RDP/tfidf/PredictionsRData/kFoldCrossValidationSetup/CREST_LAB/CREST-master/LCAClassifier/eggs/setuptools-36.2.0-py2.7.egg/setuptools/command/easy_install.py", line 698, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/adithya/RDP/tfidf/PredictionsRData/kFoldCrossValidationSetup/CREST_LAB/CREST-master/LCAClassifier/eggs/setuptools-36.2.0-py2.7.egg/setuptools/command/easy_install.py", line 879, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/adithya/RDP/tfidf/PredictionsRData/kFoldCrossValidationSetup/CREST_LAB/CREST-master/LCAClassifier/eggs/setuptools-36.2.0-py2.7.egg/setuptools/command/easy_install.py", line 1118, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/adithya/RDP/tfidf/PredictionsRData/kFoldCrossValidationSetup/CREST_LAB/CREST-master/LCAClassifier/eggs/setuptools-36.2.0-py2.7.egg/setuptools/command/easy_install.py", line 1104, in run_setup
    run_setup(setup_script, args)
  File "/home/adithya/RDP/tfidf/PredictionsRData/kFoldCrossValidationSetup/CREST_LAB/CREST-master/LCAClassifier/eggs/setuptools-36.2.0-py2.7.egg/setuptools/sandbox.py", line 257, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/adithya/RDP/tfidf/PredictionsRData/kFoldCrossValidationSetup/CREST_LAB/CREST-master/LCAClassifier/eggs/setuptools-36.2.0-py2.7.egg/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/adithya/RDP/tfidf/PredictionsRData/kFoldCrossValidationSetup/CREST_LAB/CREST-master/LCAClassifier/eggs/setuptools-36.2.0-py2.7.egg/setuptools/sandbox.py", line 170, in save_modules
    saved_exc.resume()
  File "/home/adithya/RDP/tfidf/PredictionsRData/kFoldCrossValidationSetup/CREST_LAB/CREST-master/LCAClassifier/eggs/setuptools-36.2.0-py2.7.egg/setuptools/sandbox.py", line 145, in resume
    six.reraise(type, exc, self._tb)
  File "/home/adithya/RDP/tfidf/PredictionsRData/kFoldCrossValidationSetup/CREST_LAB/CREST-master/LCAClassifier/eggs/setuptools-36.2.0-py2.7.egg/setuptools/sandbox.py", line 158, in save_modules
    yield saved
  File "/home/adithya/RDP/tfidf/PredictionsRData/kFoldCrossValidationSetup/CREST_LAB/CREST-master/LCAClassifier/eggs/setuptools-36.2.0-py2.7.egg/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/home/adithya/RDP/tfidf/PredictionsRData/kFoldCrossValidationSetup/CREST_LAB/CREST-master/LCAClassifier/eggs/setuptools-36.2.0-py2.7.egg/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/home/adithya/RDP/tfidf/PredictionsRData/kFoldCrossValidationSetup/CREST_LAB/CREST-master/LCAClassifier/eggs/setuptools-36.2.0-py2.7.egg/setuptools/sandbox.py", line 49, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-1bDRHT/biom-format-2.1.6/setup.py", line 20, in <module>
    packages=find_packages('src', exclude=['ez_setup']),
ImportError: numpy must be installed prior to installing biom
An error occurred when trying to install biom-format 2.1.6. Look above this message for any errors that were output by easy_install.
While:
  Installing test.
  Getting distribution for 'biom-format>1.1.1'.
Error: Couldn't install: biom-format 2.1.6
`

Can you help me out with this?

**Comment by lanzen** [comment]
Hi,

This is the issue with installing BIOM-tools which require numpy. I believe that it should work in the development version. Could you try to use git clone https://github.com/lanzen/CREST and then install it in the same manner? Like this you will also get a pre-release version of the SilvaMod128 that is still being finished, but with very minor changes to the taxonomy.

**Comment by TurbulentCupcake** [comment]
Hey,

I tried git clone, ran ./install and ran into the same issue. Is there any other way around it?

**Comment by lanzen** [comment]
This is basically a biom-format or numpy issue. Can you try installing them, in that order, without CREST and setuptools? I really liked the old self installing setuptools and it will take a lot of work to change how CREST installs, but it no longer seems to be supported. I am not sure if that is the issue or something else, however. Basically, biom-format and numpy seem to be very sensitive to Linux-distros etc. and it seems really random when you get installation issues with them.

You could edit the files setup.py and buildout.cfg and comment out the line in each that contains the word biom-tools. Then, you will no longter be able to use OTU tables in BIOM format but you may not need that function anyway?

**Comment by TurbulentCupcake** [comment]
couldn't find the words 'biom-tools', but I found 'biom-format' and commented those out

**Comment by TurbulentCupcake** [comment]
Oops, wrong button.. 

Anyway, i couldn't find 'biom-tools' but found 'biom-format', unsure but are they the same?

**Comment by lanzen** [comment]
Sorry for not replying in a while. Yes, I meant "biom-format" before, sorry. You will have to go to the src/LCAClassifier/classify.py and comment out lines 31-32 as well (import biom-table and biom-parse), otherwise this will give you a runtime error. Let me know if this helped

**Comment by lanzen** [comment]
Hi, I just updated the silvamod128 database to correct a few minor error in the pre-release version that was there before. This means that you have to update the development version from github in case your installation never reached far enough to download the database files, otherwise you will get a checksum control error. Just type git pull. Make sure the biom related lines are still commented out.

**Comment by lanzen** [comment]
I have now locked biom-format to an older version after looking at a similar installation problem from forced installation of numpy although it should not be necessary. This seems to be occuring whenever biom-format >2.0 is installed. Please try to update the source release to the latest version (git pull) and try to install again. I will include this in a minor bug fix release asap.
